version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: bcube-postgres
    environment:
      POSTGRES_DB: bcube
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcube-network

volumes:
  postgres-data:

networks:
  bcube-network: