spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

user-service.base-url=${USER_SERVICE_BASE_URL}
studio-service.base-url=${STUDIO_SERVICE_BASE_URL}
payment-service.base-url=http://payment-service:8085/api/payments
notification-service.base-url=http://user-service:8080/api/notifications
internal.service-key=${INTERNAL_SERVICE_KEY}