SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_table_access_method = heap;
CREATE TABLE public.payments (
    id bigint NOT NULL,
    base_amount_cents integer NOT NULL,
    booking_date date,
    booking_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    currency character varying(255) NOT NULL,
    discount_amount_cents integer NOT NULL,
    duration_hours numeric(38,2) NOT NULL,
    final_amount_cents integer NOT NULL,
    hourly_rate_cents_snapshot integer NOT NULL,
    refunded_amount_cents integer NOT NULL,
    status character varying(255) NOT NULL,
    stripe_payment_intent_id character varying(255),
    stripe_refund_id character varying(255),
    studio_id bigint NOT NULL,
    studio_name character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    voucher_id bigint,
    stripe_setup_intent_id character varying(255),
    invoice_issued_at timestamp(6) with time zone,
    invoice_number character varying(255),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'REQUIRES_PAYMENT'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying, 'FREE'::character varying, 'REFUNDED'::character varying, 'PARTIALLY_REFUNDED'::character varying])::text[])))
);
ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.voucher_redemptions (
    id bigint NOT NULL,
    booking_id bigint,
    card_fingerprint character varying(255),
    expires_at timestamp(6) with time zone,
    granted_at timestamp(6) with time zone NOT NULL,
    payment_id bigint,
    phone_hash character varying(255),
    redeemed_at timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    voucher_id bigint NOT NULL,
    CONSTRAINT voucher_redemptions_status_check CHECK (((status)::text = ANY ((ARRAY['GRANTED'::character varying, 'REDEEMED'::character varying, 'EXPIRED'::character varying])::text[])))
);
ALTER TABLE public.voucher_redemptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_redemptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.vouchers (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    discount_amount_cents integer,
    discount_hours numeric(38,2),
    discount_percentage integer,
    discount_type character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone,
    max_redemptions_per_user integer NOT NULL,
    max_redemptions_total integer,
    name character varying(255) NOT NULL,
    requires_card_verification boolean NOT NULL,
    CONSTRAINT vouchers_discount_type_check CHECK (((discount_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FIXED_AMOUNT'::character varying, 'FREE_HOURS'::character varying])::text[])))
);
ALTER TABLE public.vouchers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT uk30ftp2biebbvpik8e49wlmady UNIQUE (code);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk4bgtvbut8seryy8kitym8sfgq UNIQUE (invoice_number);
ALTER TABLE ONLY public.voucher_redemptions
    ADD CONSTRAINT voucher_redemptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);
