SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_table_access_method = heap;
CREATE TABLE public.booking_ip_events (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    event_type character varying(255) NOT NULL,
    ip_address character varying(255) NOT NULL,
    CONSTRAINT booking_ip_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['BOOK'::character varying, 'CANCEL'::character varying])::text[])))
);
ALTER TABLE public.booking_ip_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_ip_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.bookings (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    date date NOT NULL,
    end_time timestamp(6) with time zone NOT NULL,
    start_time timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    studio_id bigint NOT NULL,
    user_id bigint NOT NULL,
    smartlock_id bigint,
    reminder_sent_at timestamp(6) with time zone,
    CONSTRAINT bookings_status_check CHECK (((status)::text = ANY ((ARRAY['CONFIRMED'::character varying, 'PENDING'::character varying, 'FAILED'::character varying, 'DONE'::character varying, 'CANCELLED'::character varying])::text[])))
);
ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.ip_bans (
    id bigint NOT NULL,
    ban_count integer NOT NULL,
    banned_at timestamp(6) with time zone NOT NULL,
    banned_until timestamp(6) with time zone NOT NULL,
    ip_address character varying(255) NOT NULL
);
ALTER TABLE public.ip_bans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ip_bans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.booking_ip_events
    ADD CONSTRAINT booking_ip_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ip_bans
    ADD CONSTRAINT ip_bans_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ip_bans
    ADD CONSTRAINT ukisptspefjt3u6oyv7btvl6qc9 UNIQUE (ip_address);
