SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_table_access_method = heap;
CREATE TABLE public.studios (
    id bigint NOT NULL,
    city character varying(50) NOT NULL,
    country character varying(50) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(1000) NOT NULL,
    image_data oid,
    image_gallery_json text,
    is_active boolean NOT NULL,
    latitude double precision,
    longitude double precision,
    name character varying(50) NOT NULL,
    plz integer NOT NULL,
    smartlock_id bigint NOT NULL,
    street character varying(50) NOT NULL,
    hourly_rate_cents integer
);
ALTER TABLE public.studios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.studios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.studios
    ADD CONSTRAINT studios_pkey PRIMARY KEY (id);
